---
- name: Sysctl | Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-disable-ipv6.conf
    reload: true
  with_items:
    - {name: net.ipv6.conf.all.disable_ipv6, value: 1}
    - {name: net.ipv6.conf.default.disable_ipv6, value: 1}
    - {name: net.ipv6.conf.lo.disable_ipv6, value: 1}

- name: Sysctl | Enable ipv4 forwarding
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/10-enable-ipv4-forwarding.conf
    reload: true
  with_items:
    - {name: net.ipv4.ip_forward, value: 1}

- name: Sysctl | Inotify
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-inotify.conf
    reload: true
  with_items:
    - {name: fs.inotify.max_user_instances, value: 512}
    - {name: fs.inotify.max_user_watches, value: 2097152}
  tags:
    - inotify
