---
- name: Hashicorp | Add apt key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Hasicorp | Add repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hasicorp

- name: Hasicorp | Install
  ansible.builtin.apt:
    name:
      - terraform
      - vault
      - packer
    state: latest
    update_cache: true

- name: TF | Configure .terraformrc
  ansible.builtin.copy:
    content: |
      plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
      provider_installation { network_mirror { url = "https://registry.comcloud.xyz/" } }
    dest: "{{ user_home }}/.terraformrc"
    mode: "0644"

- name: TF | Create cache directory
  ansible.builtin.file:
    path: "{{ user_home }}/.terraform.d/plugin-cache"
    state: directory
    owner: "{{ user_name }}"
    mode: "0755"
