---
# - name: Hashicorp | Add apt key
#   ansible.builtin.apt_key:
#     url: https://apt.releases.hashicorp.com/gpg
#     keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

# - name: Hasicorp | Add repo
#   ansible.builtin.apt_repository:
#     repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
#     state: present
#     filename: hasicorp

# - name: Hasicorp | Install
#   ansible.builtin.apt:
#     name:
#       - terraform
#       - vault
#       - packer
#     state: latest
#     update_cache: true
- name: Install TF
  tags: [tf, terrafrom]
  vars:
    tf_plugins_cache_dir: "{{ user_home }}/.terraform.d/plugin-cache"
    tf_plugins_dir: "{{ user_home }}/.terraform.d/plugins/linux_amd64"
  block:
  - name: TF | Create cache directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ user_name }}"
      mode: "0755"
    with_items:
    - "{{ tf_plugins_cache_dir }}"
    - "{{ tf_plugins_dir }}"

  - name: TF | Configure .terraformrc
    ansible.builtin.copy:
    #  content: |
    #   plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
    #   provider_installation { network_mirror { url = "https://registry.comcloud.xyz/" } }

      # https://nm.tf.org.ru/
      content: |
        plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
        provider_installation {
          // network_mirror {
          //   url     = "https://registry.comcloud.xyz/"
          //   include = ["registry.terraform.io/*/*"]
          // }
          // direct {
          //   exclude = ["registry.terraform.io/*/*"]
          // }
          filesystem_mirror {
            path    = "{{ tf_plugins_dir }}"
            include = ["*/*/*"]
          }
        }
      dest: "{{ user_home }}/.terraformrc"
      mode: "0644"


  - name: TF | Install terraform {{ tf_ver }}
    vars:
      #tf_ver: 1.7.1
      tf_ver: 0.13.4
      #tf_ver: 0.14.8
    ansible.builtin.unarchive:
      src: "https://releases.comcloud.xyz/terraform/{{ tf_ver }}/terraform_{{ tf_ver }}_linux_amd64.zip"
      dest: /usr/local/bin/
      remote_src: true
      mode: 0755

  - name: TF | Install terraform providers
    tags:
      - tf_provider
    vars:
      terraform_provider_k8s_ver: 1.0.6
      plugin_dir: "{{ tf_plugins_dir }}/registry.terraform.io/mingfang/k8s/{{ terraform_provider_k8s_ver }}/linux_amd64"
    block:
    - name: TF Plugins | Create directory
      ansible.builtin.file:
        path: "{{ plugin_dir }}"
        state: directory
        owner: "{{ user_name }}"
        mode: "0755"
    - name: TF Plugins | Get provider
      ansible.builtin.unarchive:
        src: "https://github.com/mingfang/terraform-provider-k8s/releases/download/v{{ terraform_provider_k8s_ver }}/terraform-provider-k8s_{{ terraform_provider_k8s_ver }}_linux_amd64.zip"
        dest: "{{ plugin_dir }}"
        remote_src: true
        mode: 0755


- name: Packer | Install packer {{ packer_ver }}
  tags: [packer]
  vars:
    packer_ver: 1.7.1
  ansible.builtin.unarchive:
    src: "https://releases.comcloud.xyz/packer/{{ packer_ver }}/packer_{{ packer_ver }}_linux_amd64.zip"
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
