---
- name: K8s | Install k8s repo
  tags:
    - kubectl
  block:
    - name: K8s | Add key for k8s repo
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: K8s | Add k8s repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: docker

    - name: K8s | Install k8s apps
      ansible.builtin.apt:
        name:
          - kubectl
        state: latest
        update_cache: true

# https://github.com/derailed/k9s/releases
- name: K8s | Install k9s {{ k9s_ver }}
  vars:
    k9s_ver: 0.27.3
    k9s_folder: "{{ user_home }}/.config/k9s"
  tags:
    - k9s
  block:
    - name: k9s | Install k9s
      ansible.builtin.unarchive:
        src: "https://github.com/derailed/k9s/releases/download/v{{ k9s_ver }}/k9s_Linux_amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        mode: 0755

    - name: k9s | Create folder {{ k9s_folder }}
      ansible.builtin.file:
        path: "{{ k9s_folder }}"
        state: directory
        mode: "0755"

    # https://github.com/derailed/k9s/tree/master/skins
    - name: k9s | Gruvbox theme
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/derailed/k9s/master/skins/gruvbox-dark.yml
        force: true
        dest: "{{ k9s_folder }}/skin.yml"
        mode: 0644

# https://github.com/stern/stern
- name: K8s | Install stern {{ stern_ver }}
  vars:
    stern_ver: 1.23.0
  ansible.builtin.unarchive:
    src: "https://github.com/stern/stern/releases/download/v{{ stern_ver }}/stern_{{ stern_ver }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
  tags:
    - stern

- name: K8s | Install minkube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    force: true
    dest: "/usr/local/bin/minikube"
    mode: 0755
  tags:
    - minikube

# https://github.com/pulumi/kubespy
- name: K8s | Install kubespy {{ kubespy_ver }}
  vars:
    kubespy_ver: v0.6.1
  ansible.builtin.unarchive:
    src: https://github.com/pulumi/kubespy/releases/download/{{ kubespy_ver }}/kubespy-{{ kubespy_ver }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - kubespy  # extract just one file
    remote_src: true
    mode: 0755
  tags:
    - kubespy

# https://github.com/helm/helm/releases
- name: K8s | Install helm {{ helm_ver }}
  vars:
    helm_ver: v3.11.1
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_ver }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    extra_opts:
      - --strip-components=1
      - linux-amd64/helm
  tags:
    - helm

# https://github.com/kubernetes-sigs/krew
- name: K8s | Krew
  vars:
    krew_ver: v0.4.3
  tags:
    - krew
  block:
    - name: k8s | Install krew
      ansible.builtin.unarchive:
        src: https://github.com/kubernetes-sigs/krew/releases/download/{{ krew_ver }}/krew-linux_amd64.tar.gz
        dest: /tmp
        extra_opts:
          # - --strip=1
          - --wildcards
          - "*/krew-linux_amd64"
        remote_src: true

    - name: k8s | Rename krew
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/krew-linux_amd64
        dest: /usr/local/bin/krew
        mode: 0755

# https://github.com/istio/istio/releases/
- name: K8s | Install istioctl {{ istioctl_ver }}
  vars:
    istioctl_ver: 1.17.0
  ansible.builtin.unarchive:
    src: "https://github.com/istio/istio/releases/download/{{ istioctl_ver }}/istioctl-{{ istioctl_ver }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
  tags:
    - istioctl

# https://github.com/stackrox/kube-linter
- name: K8s | Install kube-linter
  vars:
    kube_linter_ver: 0.6.0
  ansible.builtin.get_url:
    url: "https://github.com/stackrox/kube-linter/releases/download/{{ kube_linter_ver }}/kube-linter-linux"
    force: true
    dest: "/usr/local/bin/kube-linter"
    mode: 0755
  tags:
    - kube-linter

# https://kind.sigs.k8s.io/
- name: K8s | Install kind
  vars:
    kind_ver: 0.17.0
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/v{{ kind_ver }}/kind-linux-amd64"
    force: true
    dest: "/usr/local/bin/kind"
    mode: 0755
  tags:
    - kind

# https://github.com/kubeshark/kubeshark
- name: K8s | Install kubeshark
  vars:
    kubeshark_ver: 38.5
  ansible.builtin.get_url:
    url: "https://github.com/kubeshark/kubeshark/releases/download/{{ kubeshark_ver }}/kubeshark_linux_amd64"
    force: true
    dest: "/usr/local/bin/kubeshark"
    mode: 0755
  tags:
    - kubeshark

# https://github.com/cilium/cilium-cli
- name: K8s | Install cilium-cli {{ cilium_cli_ver }}
  vars:
    cilium_cli_ver: v0.12.13
  ansible.builtin.unarchive:
    src: https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_ver }}/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - cilium
    remote_src: true
  tags:
    - cilium
    - cilium-cli
