---
- name: Vim | Install vim
  ansible.builtin.apt:
    name:
      - vim
    state: latest
    update_cache: true

- name: Vim | Configure vim
  ansible.builtin.copy:
    content: |
      colorscheme industry
      set number
      syntax on
      set hlsearch
      set et
      set sw=2 ts=2 sts=2
    dest: "{{ user_home }}/.vimrc"
    mode: "0644"
